<?php

namespace ContainerXLyCjc1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VzIs93cService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vzIs93c' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vzIs93c'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\MaintenanceController::delete' => ['privates', '.service_locator.vdiYExM', 'get_ServiceLocator_VdiYExMService', true],
            'App\\Controller\\MaintenanceController::edit' => ['privates', '.service_locator.vdiYExM', 'get_ServiceLocator_VdiYExMService', true],
            'App\\Controller\\MaintenanceController::index' => ['privates', '.service_locator.m5wWMwA', 'get_ServiceLocator_M5wWMwAService', true],
            'App\\Controller\\MaintenanceController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\MaintenanceController::show' => ['privates', '.service_locator.yr1nTWk', 'get_ServiceLocator_Yr1nTWkService', true],
            'App\\Controller\\TrottinetteController::delete' => ['privates', '.service_locator.bRb45ww', 'get_ServiceLocator_BRb45wwService', true],
            'App\\Controller\\TrottinetteController::edit' => ['privates', '.service_locator.2yXxVmb', 'get_ServiceLocator_2yXxVmbService', true],
            'App\\Controller\\TrottinetteController::index' => ['privates', '.service_locator.yooyB2k', 'get_ServiceLocator_YooyB2kService', true],
            'App\\Controller\\TrottinetteController::new' => ['privates', '.service_locator.SjSfHXY', 'get_ServiceLocator_SjSfHXYService', true],
            'App\\Controller\\TrottinetteController::show' => ['privates', '.service_locator.1S7vK.7', 'get_ServiceLocator_1S7vK_7Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\MaintenanceController:delete' => ['privates', '.service_locator.vdiYExM', 'get_ServiceLocator_VdiYExMService', true],
            'App\\Controller\\MaintenanceController:edit' => ['privates', '.service_locator.vdiYExM', 'get_ServiceLocator_VdiYExMService', true],
            'App\\Controller\\MaintenanceController:index' => ['privates', '.service_locator.m5wWMwA', 'get_ServiceLocator_M5wWMwAService', true],
            'App\\Controller\\MaintenanceController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\MaintenanceController:show' => ['privates', '.service_locator.yr1nTWk', 'get_ServiceLocator_Yr1nTWkService', true],
            'App\\Controller\\TrottinetteController:delete' => ['privates', '.service_locator.bRb45ww', 'get_ServiceLocator_BRb45wwService', true],
            'App\\Controller\\TrottinetteController:edit' => ['privates', '.service_locator.2yXxVmb', 'get_ServiceLocator_2yXxVmbService', true],
            'App\\Controller\\TrottinetteController:index' => ['privates', '.service_locator.yooyB2k', 'get_ServiceLocator_YooyB2kService', true],
            'App\\Controller\\TrottinetteController:new' => ['privates', '.service_locator.SjSfHXY', 'get_ServiceLocator_SjSfHXYService', true],
            'App\\Controller\\TrottinetteController:show' => ['privates', '.service_locator.1S7vK.7', 'get_ServiceLocator_1S7vK_7Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\MaintenanceController::delete' => '?',
            'App\\Controller\\MaintenanceController::edit' => '?',
            'App\\Controller\\MaintenanceController::index' => '?',
            'App\\Controller\\MaintenanceController::new' => '?',
            'App\\Controller\\MaintenanceController::show' => '?',
            'App\\Controller\\TrottinetteController::delete' => '?',
            'App\\Controller\\TrottinetteController::edit' => '?',
            'App\\Controller\\TrottinetteController::index' => '?',
            'App\\Controller\\TrottinetteController::new' => '?',
            'App\\Controller\\TrottinetteController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\MaintenanceController:delete' => '?',
            'App\\Controller\\MaintenanceController:edit' => '?',
            'App\\Controller\\MaintenanceController:index' => '?',
            'App\\Controller\\MaintenanceController:new' => '?',
            'App\\Controller\\MaintenanceController:show' => '?',
            'App\\Controller\\TrottinetteController:delete' => '?',
            'App\\Controller\\TrottinetteController:edit' => '?',
            'App\\Controller\\TrottinetteController:index' => '?',
            'App\\Controller\\TrottinetteController:new' => '?',
            'App\\Controller\\TrottinetteController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
