<?php

namespace ContainerXLyCjc1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VdiYExMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vdiYExM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vdiYExM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'maintenance' => ['privates', '.errored..service_locator.vdiYExM.App\\Entity\\Maintenance', NULL, 'Cannot autowire service ".service_locator.vdiYExM": it needs an instance of "App\\Entity\\Maintenance" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'maintenance' => 'App\\Entity\\Maintenance',
        ]);
    }
}
