<?php

namespace ContainerXLyCjc1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaintenanceTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\MaintenanceType' shared autowired service.
     *
     * @return \App\Form\MaintenanceType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\MaintenanceType'] = new \App\Form\MaintenanceType();
    }
}
