<?php

namespace ContainerXLyCjc1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrottinette2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.2yXxVmb.App\Entity\Trottinette' shared service.
     *
     * @return \App\Entity\Trottinette
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.2yXxVmb": it needs an instance of "App\\Entity\\Trottinette" but this type has been excluded in "config/services.yaml".');
    }
}
