symfonycasts_reset_password:
  request_password_repository: App\Repository\ResetPasswordRequestRepository
  lifetime: 3600 # Token lifetime in seconds (1 hour)
  # throttle_requests: true # Enable for production to prevent spamming
  # sender_email: 'noreply@yourdomain.com' # Optional: Set a default sender
  # sender_name: 'Password Reset Bot'   # Optional: Set a default sender name