<?php

namespace Container1Jq8g7Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MS_BfckService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mS.bfck' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mS.bfck'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'eventRepository' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
            'participationRepository' => ['privates', 'App\\Repository\\ParticipationRepository', 'getParticipationRepositoryService', true],
            'pointRelaisRepository' => ['privates', 'App\\Repository\\PointRelaisRepository', 'getPointRelaisRepositoryService', true],
            'reservationrepo' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'trottinetteRepository' => ['services', 'App\\Repository\\TrottinetteRepository', 'getTrottinetteRepositoryService', true],
        ], [
            'eventRepository' => 'App\\Repository\\EventRepository',
            'participationRepository' => 'App\\Repository\\ParticipationRepository',
            'pointRelaisRepository' => 'App\\Repository\\PointRelaisRepository',
            'reservationrepo' => 'App\\Repository\\ReservationRepository',
            'trottinetteRepository' => 'App\\Repository\\TrottinetteRepository',
        ]);
    }
}
