<?php

namespace Container1Jq8g7Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_66pfiUbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.66pfiUb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.66pfiUb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trottiRepo' => ['services', 'App\\Repository\\TrottinetteRepository', 'getTrottinetteRepositoryService', true],
        ], [
            'trottiRepo' => 'App\\Repository\\TrottinetteRepository',
        ]);
    }
}
