<?php

namespace ContainerKaqYNw5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9bGKCoGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9bGKCoG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9bGKCoG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'event' => ['privates', '.errored..service_locator.9bGKCoG.App\\Entity\\Event', NULL, 'Cannot autowire service ".service_locator.9bGKCoG": it needs an instance of "App\\Entity\\Event" but this type has been excluded in "config/services.yaml".'],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'participationRepository' => ['privates', 'App\\Repository\\ParticipationRepository', 'getParticipationRepositoryService', true],
        ], [
            'event' => 'App\\Entity\\Event',
            'paginator' => '?',
            'participationRepository' => 'App\\Repository\\ParticipationRepository',
        ]);
    }
}
