<?php

namespace ContainerDX6iwxq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OvY6YvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ov_y6Yv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ov_y6Yv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pointRelais' => ['privates', '.errored..service_locator.Ov_y6Yv.App\\Entity\\PointRelais', NULL, 'Cannot autowire service ".service_locator.Ov_y6Yv": it needs an instance of "App\\Entity\\PointRelais" but this type has been excluded in "config/services.yaml".'],
        ], [
            'pointRelais' => 'App\\Entity\\PointRelais',
        ]);
    }
}
