<?php

namespace ContainerGGZefcR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__SntuEMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..SntuEM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..SntuEM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'eventRepository' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
            'reservationRepo' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'trottinetteRepo' => ['services', 'App\\Repository\\TrottinetteRepository', 'getTrottinetteRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'eventRepository' => 'App\\Repository\\EventRepository',
            'reservationRepo' => 'App\\Repository\\ReservationRepository',
            'trottinetteRepo' => 'App\\Repository\\TrottinetteRepository',
            'userRepo' => 'App\\Repository\\UtilisateurRepository',
        ]);
    }
}
