<?php

namespace ContainerL0tGikI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PwdIMQrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pwdIMQr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pwdIMQr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AdminController::dashboard' => ['privates', '.service_locator.48q8zSl', 'get_ServiceLocator_48q8zSlService', true],
            'App\\Controller\\AdminController::delete' => ['privates', '.service_locator.dANsewa', 'get_ServiceLocator_DANsewaService', true],
            'App\\Controller\\AdminController::edit' => ['privates', '.service_locator.dANsewa', 'get_ServiceLocator_DANsewaService', true],
            'App\\Controller\\AdminController::eventParticipants' => ['privates', '.service_locator.Y2F5Zqo', 'get_ServiceLocator_Y2F5ZqoService', true],
            'App\\Controller\\AdminController::events' => ['privates', '.service_locator.qE8Flyf', 'get_ServiceLocator_QE8FlyfService', true],
            'App\\Controller\\AdminController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\EventController::cancel' => ['privates', '.service_locator.rx24Tj0', 'get_ServiceLocator_Rx24Tj0Service', true],
            'App\\Controller\\EventController::delete' => ['privates', '.service_locator.dANsewa', 'get_ServiceLocator_DANsewaService', true],
            'App\\Controller\\EventController::edit' => ['privates', '.service_locator.dANsewa', 'get_ServiceLocator_DANsewaService', true],
            'App\\Controller\\EventController::index' => ['privates', '.service_locator.RZIBQhN', 'get_ServiceLocator_RZIBQhNService', true],
            'App\\Controller\\EventController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\EventController::participants' => ['privates', '.service_locator.9bGKCoG', 'get_ServiceLocator_9bGKCoGService', true],
            'App\\Controller\\EventController::participate' => ['privates', '.service_locator.w.iWOof', 'get_ServiceLocator_W_IWOofService', true],
            'App\\Controller\\EventController::publicList' => ['privates', '.service_locator.qE8Flyf', 'get_ServiceLocator_QE8FlyfService', true],
            'App\\Controller\\EventController::show' => ['privates', '.service_locator.Y2F5Zqo', 'get_ServiceLocator_Y2F5ZqoService', true],
            'App\\Controller\\PublicEventController::events' => ['privates', '.service_locator.qE8Flyf', 'get_ServiceLocator_QE8FlyfService', true],
            'App\\Controller\\PublicEventController::participate' => ['privates', '.service_locator.w.iWOof', 'get_ServiceLocator_W_IWOofService', true],
            'App\\Controller\\PublicEventController::show' => ['privates', '.service_locator.Y2F5Zqo', 'get_ServiceLocator_Y2F5ZqoService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdminController:dashboard' => ['privates', '.service_locator.48q8zSl', 'get_ServiceLocator_48q8zSlService', true],
            'App\\Controller\\AdminController:delete' => ['privates', '.service_locator.dANsewa', 'get_ServiceLocator_DANsewaService', true],
            'App\\Controller\\AdminController:edit' => ['privates', '.service_locator.dANsewa', 'get_ServiceLocator_DANsewaService', true],
            'App\\Controller\\AdminController:eventParticipants' => ['privates', '.service_locator.Y2F5Zqo', 'get_ServiceLocator_Y2F5ZqoService', true],
            'App\\Controller\\AdminController:events' => ['privates', '.service_locator.qE8Flyf', 'get_ServiceLocator_QE8FlyfService', true],
            'App\\Controller\\AdminController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\EventController:cancel' => ['privates', '.service_locator.rx24Tj0', 'get_ServiceLocator_Rx24Tj0Service', true],
            'App\\Controller\\EventController:delete' => ['privates', '.service_locator.dANsewa', 'get_ServiceLocator_DANsewaService', true],
            'App\\Controller\\EventController:edit' => ['privates', '.service_locator.dANsewa', 'get_ServiceLocator_DANsewaService', true],
            'App\\Controller\\EventController:index' => ['privates', '.service_locator.RZIBQhN', 'get_ServiceLocator_RZIBQhNService', true],
            'App\\Controller\\EventController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\EventController:participants' => ['privates', '.service_locator.9bGKCoG', 'get_ServiceLocator_9bGKCoGService', true],
            'App\\Controller\\EventController:participate' => ['privates', '.service_locator.w.iWOof', 'get_ServiceLocator_W_IWOofService', true],
            'App\\Controller\\EventController:publicList' => ['privates', '.service_locator.qE8Flyf', 'get_ServiceLocator_QE8FlyfService', true],
            'App\\Controller\\EventController:show' => ['privates', '.service_locator.Y2F5Zqo', 'get_ServiceLocator_Y2F5ZqoService', true],
            'App\\Controller\\PublicEventController:events' => ['privates', '.service_locator.qE8Flyf', 'get_ServiceLocator_QE8FlyfService', true],
            'App\\Controller\\PublicEventController:participate' => ['privates', '.service_locator.w.iWOof', 'get_ServiceLocator_W_IWOofService', true],
            'App\\Controller\\PublicEventController:show' => ['privates', '.service_locator.Y2F5Zqo', 'get_ServiceLocator_Y2F5ZqoService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AdminController::dashboard' => '?',
            'App\\Controller\\AdminController::delete' => '?',
            'App\\Controller\\AdminController::edit' => '?',
            'App\\Controller\\AdminController::eventParticipants' => '?',
            'App\\Controller\\AdminController::events' => '?',
            'App\\Controller\\AdminController::new' => '?',
            'App\\Controller\\EventController::cancel' => '?',
            'App\\Controller\\EventController::delete' => '?',
            'App\\Controller\\EventController::edit' => '?',
            'App\\Controller\\EventController::index' => '?',
            'App\\Controller\\EventController::new' => '?',
            'App\\Controller\\EventController::participants' => '?',
            'App\\Controller\\EventController::participate' => '?',
            'App\\Controller\\EventController::publicList' => '?',
            'App\\Controller\\EventController::show' => '?',
            'App\\Controller\\PublicEventController::events' => '?',
            'App\\Controller\\PublicEventController::participate' => '?',
            'App\\Controller\\PublicEventController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminController:dashboard' => '?',
            'App\\Controller\\AdminController:delete' => '?',
            'App\\Controller\\AdminController:edit' => '?',
            'App\\Controller\\AdminController:eventParticipants' => '?',
            'App\\Controller\\AdminController:events' => '?',
            'App\\Controller\\AdminController:new' => '?',
            'App\\Controller\\EventController:cancel' => '?',
            'App\\Controller\\EventController:delete' => '?',
            'App\\Controller\\EventController:edit' => '?',
            'App\\Controller\\EventController:index' => '?',
            'App\\Controller\\EventController:new' => '?',
            'App\\Controller\\EventController:participants' => '?',
            'App\\Controller\\EventController:participate' => '?',
            'App\\Controller\\EventController:publicList' => '?',
            'App\\Controller\\EventController:show' => '?',
            'App\\Controller\\PublicEventController:events' => '?',
            'App\\Controller\\PublicEventController:participate' => '?',
            'App\\Controller\\PublicEventController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
