<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL0tGikI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL0tGikI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL0tGikI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL0tGikI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL0tGikI\App_KernelDevDebugContainer([
    'container.build_hash' => 'L0tGikI',
    'container.build_id' => 'a840c98c',
    'container.build_time' => 1744554234,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL0tGikI');
