<?php

namespace Container7EBefYq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SmW0xStService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SmW0xSt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SmW0xSt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\PointRelaisController::delete' => ['privates', '.service_locator.ajGjC7m', 'get_ServiceLocator_AjGjC7mService', true],
            'App\\Controller\\PointRelaisController::edit' => ['privates', '.service_locator.ajGjC7m', 'get_ServiceLocator_AjGjC7mService', true],
            'App\\Controller\\PointRelaisController::index' => ['privates', '.service_locator.Gk6LRRs', 'get_ServiceLocator_Gk6LRRsService', true],
            'App\\Controller\\PointRelaisController::new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\PointRelaisController::show' => ['privates', '.service_locator.Ov_y6Yv', 'get_ServiceLocator_OvY6YvService', true],
            'App\\Controller\\ReservationController::delete' => ['privates', '.service_locator.rNyJSA0', 'get_ServiceLocator_RNyJSA0Service', true],
            'App\\Controller\\ReservationController::edit' => ['privates', '.service_locator.rNyJSA0', 'get_ServiceLocator_RNyJSA0Service', true],
            'App\\Controller\\ReservationController::index' => ['privates', '.service_locator.caJHb8S', 'get_ServiceLocator_CaJHb8SService', true],
            'App\\Controller\\ReservationController::new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ReservationController::show' => ['privates', '.service_locator.h9c0uBq', 'get_ServiceLocator_H9c0uBqService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\PointRelaisController:delete' => ['privates', '.service_locator.ajGjC7m', 'get_ServiceLocator_AjGjC7mService', true],
            'App\\Controller\\PointRelaisController:edit' => ['privates', '.service_locator.ajGjC7m', 'get_ServiceLocator_AjGjC7mService', true],
            'App\\Controller\\PointRelaisController:index' => ['privates', '.service_locator.Gk6LRRs', 'get_ServiceLocator_Gk6LRRsService', true],
            'App\\Controller\\PointRelaisController:new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\PointRelaisController:show' => ['privates', '.service_locator.Ov_y6Yv', 'get_ServiceLocator_OvY6YvService', true],
            'App\\Controller\\ReservationController:delete' => ['privates', '.service_locator.rNyJSA0', 'get_ServiceLocator_RNyJSA0Service', true],
            'App\\Controller\\ReservationController:edit' => ['privates', '.service_locator.rNyJSA0', 'get_ServiceLocator_RNyJSA0Service', true],
            'App\\Controller\\ReservationController:index' => ['privates', '.service_locator.caJHb8S', 'get_ServiceLocator_CaJHb8SService', true],
            'App\\Controller\\ReservationController:new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ReservationController:show' => ['privates', '.service_locator.h9c0uBq', 'get_ServiceLocator_H9c0uBqService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\PointRelaisController::delete' => '?',
            'App\\Controller\\PointRelaisController::edit' => '?',
            'App\\Controller\\PointRelaisController::index' => '?',
            'App\\Controller\\PointRelaisController::new' => '?',
            'App\\Controller\\PointRelaisController::show' => '?',
            'App\\Controller\\ReservationController::delete' => '?',
            'App\\Controller\\ReservationController::edit' => '?',
            'App\\Controller\\ReservationController::index' => '?',
            'App\\Controller\\ReservationController::new' => '?',
            'App\\Controller\\ReservationController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\PointRelaisController:delete' => '?',
            'App\\Controller\\PointRelaisController:edit' => '?',
            'App\\Controller\\PointRelaisController:index' => '?',
            'App\\Controller\\PointRelaisController:new' => '?',
            'App\\Controller\\PointRelaisController:show' => '?',
            'App\\Controller\\ReservationController:delete' => '?',
            'App\\Controller\\ReservationController:edit' => '?',
            'App\\Controller\\ReservationController:index' => '?',
            'App\\Controller\\ReservationController:new' => '?',
            'App\\Controller\\ReservationController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
