<?php

namespace ContainerZCYBfzV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A1S6hbfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.a1S6hbf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a1S6hbf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chatbotService' => ['privates', 'App\\Service\\ChatbotService', 'getChatbotServiceService', true],
        ], [
            'chatbotService' => 'App\\Service\\ChatbotService',
        ]);
    }
}
