<?php

namespace ContainerZCYBfzV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AjGjC7mService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ajGjC7m' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ajGjC7m'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'pointRelais' => ['privates', '.errored..service_locator.ajGjC7m.App\\Entity\\PointRelais', NULL, 'Cannot autowire service ".service_locator.ajGjC7m": it needs an instance of "App\\Entity\\PointRelais" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'pointRelais' => 'App\\Entity\\PointRelais',
        ]);
    }
}
