<?php

namespace ContainerZCYBfzV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A9SvP7EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.a9SvP7E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a9SvP7E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reclamationRepository' => ['privates', 'App\\Repository\\ReclamationRepository', 'getReclamationRepositoryService', true],
            'smsService' => ['privates', 'App\\Service\\SmsService', NULL, 'Cannot autowire service "App\\Service\\SmsService": argument "$twilioSid" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
        ], [
            'reclamationRepository' => 'App\\Repository\\ReclamationRepository',
            'smsService' => 'App\\Service\\SmsService',
        ]);
    }
}
