<?php

namespace ContainerZCYBfzV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QP_YFX8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QP.yFX8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QP.yFX8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'event' => ['privates', '.errored..service_locator.QP.yFX8.App\\Entity\\Event', NULL, 'Cannot autowire service ".service_locator.QP.yFX8": it needs an instance of "App\\Entity\\Event" but this type has been excluded in "config/services.yaml".'],
            'participationRepo' => ['privates', 'App\\Repository\\ParticipationRepository', 'getParticipationRepositoryService', true],
        ], [
            'event' => 'App\\Entity\\Event',
            'participationRepo' => 'App\\Repository\\ParticipationRepository',
        ]);
    }
}
