<?php

namespace ContainerZCYBfzV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1xv8E3lService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1xv8E3l' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1xv8E3l'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'trottinetteRepository' => ['services', 'App\\Repository\\TrottinetteRepository', 'getTrottinetteRepositoryService', true],
        ], [
            'paginator' => '?',
            'trottinetteRepository' => 'App\\Repository\\TrottinetteRepository',
        ]);
    }
}
