<?php

namespace ContainerZCYBfzV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BRb45wwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bRb45ww' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bRb45ww'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'trottinette' => ['privates', '.errored..service_locator.bRb45ww.App\\Entity\\Trottinette', NULL, 'Cannot autowire service ".service_locator.bRb45ww": it needs an instance of "App\\Entity\\Trottinette" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'trottinette' => 'App\\Entity\\Trottinette',
        ]);
    }
}
