<?php

namespace ContainerZCYBfzV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Il9dC4yService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Il9dC4y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Il9dC4y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'faceRecService' => ['privates', 'App\\Service\\FacialRecognitionService', 'getFacialRecognitionServiceService', true],
            'tokenStorage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
            'userRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'faceRecService' => 'App\\Service\\FacialRecognitionService',
            'tokenStorage' => '?',
            'userRepository' => 'App\\Repository\\UtilisateurRepository',
        ]);
    }
}
