<?php

namespace ContainerZCYBfzV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gk6LRRsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Gk6LRRs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gk6LRRs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pointRelaisRepository' => ['privates', 'App\\Repository\\PointRelaisRepository', 'getPointRelaisRepositoryService', true],
        ], [
            'pointRelaisRepository' => 'App\\Repository\\PointRelaisRepository',
        ]);
    }
}
