<?php

namespace ContainerZCYBfzV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatbotServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ChatbotService' shared autowired service.
     *
     * @return \App\Service\ChatbotService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ChatbotService.php';

        return $container->privates['App\\Service\\ChatbotService'] = new \App\Service\ChatbotService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)));
    }
}
