<?php

namespace ContainerZCYBfzV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFacialRecognitionServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\FacialRecognitionService' shared autowired service.
     *
     * @return \App\Service\FacialRecognitionService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/FacialRecognitionService.php';

        return $container->privates['App\\Service\\FacialRecognitionService'] = new \App\Service\FacialRecognitionService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $container->getEnv('resolve:FACE_RECOGNITION_API_ENDPOINT'));
    }
}
