<?php

namespace ContainerZCYBfzV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotifierInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Symfony\Component\Notifier\NotifierInterface' shared autowired service.
     *
     * @return \Symfony\Component\Notifier\NotifierInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/notifier/NotifierInterface.php';

        return $container->services['Symfony\\Component\\Notifier\\NotifierInterface'] = new \Symfony\Component\Notifier\NotifierInterface();
    }
}
