<?php

namespace ContainerZCYBfzV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublicEventControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PublicEventController' shared autowired service.
     *
     * @return \App\Controller\PublicEventController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PublicEventController.php';
        include_once \dirname(__DIR__, 4).'/vendor/endroid/qr-code/src/Builder/BuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/endroid/qr-code/src/Builder/Builder.php';

        $container->services['App\\Controller\\PublicEventController'] = $instance = new \App\Controller\PublicEventController(($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ($container->privates['App\\Repository\\EventRepository'] ?? $container->load('getEventRepositoryService')), ($container->privates['App\\Repository\\ParticipationRepository'] ?? $container->load('getParticipationRepositoryService')), ($container->privates['Endroid\\QrCode\\Builder\\Builder'] ??= new \Endroid\QrCode\Builder\Builder()), ($container->services['knp_snappy.pdf'] ?? $container->load('getKnpSnappy_PdfService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\PublicEventController', $container));

        return $instance;
    }
}
