<?php

namespace ContainerZCYBfzV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublicTrottinetteControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Public\PublicTrottinetteController' shared autowired service.
     *
     * @return \App\Controller\Public\PublicTrottinetteController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Public/PublicTrottinetteController.php';

        $container->services['App\\Controller\\Public\\PublicTrottinetteController'] = $instance = new \App\Controller\Public\PublicTrottinetteController(($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Public\\PublicTrottinetteController', $container));

        return $instance;
    }
}
