<?php

namespace ContainerZCYBfzV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPointRelaisService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Ov_y6Yv.App\Entity\PointRelais' shared service.
     *
     * @return \App\Entity\PointRelais
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Ov_y6Yv": it needs an instance of "App\\Entity\\PointRelais" but this type has been excluded in "config/services.yaml".');
    }
}
