<?php

namespace ContainerZCYBfzV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecaptchaV2ValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\RecaptchaV2Validator' shared autowired service.
     *
     * @return \App\Validator\RecaptchaV2Validator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Validator/RecaptchaV2Validator.php';

        return $container->privates['App\\Validator\\RecaptchaV2Validator'] = new \App\Validator\RecaptchaV2Validator(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $container->getEnv('RECAPTCHA_V2_SECRET_KEY'), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
