<?php

namespace ContainerZCYBfzV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrottinetteController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Partenaire\TrottinetteController' shared autowired service.
     *
     * @return \App\Controller\Partenaire\TrottinetteController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Partenaire/TrottinetteController.php';

        $container->services['App\\Controller\\Partenaire\\TrottinetteController'] = $instance = new \App\Controller\Partenaire\TrottinetteController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Partenaire\\TrottinetteController', $container));

        return $instance;
    }
}
