<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXq72rYN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXq72rYN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXq72rYN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXq72rYN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXq72rYN\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xq72rYN',
    'container.build_id' => 'b194de1e',
    'container.build_time' => 1744284591,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXq72rYN');
