<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBAqn0O7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBAqn0O7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBAqn0O7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBAqn0O7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBAqn0O7\App_KernelDevDebugContainer([
    'container.build_hash' => 'BAqn0O7',
    'container.build_id' => '51d02337',
    'container.build_time' => 1743945525,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBAqn0O7');
