<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMMBCceX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMMBCceX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMMBCceX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMMBCceX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMMBCceX\App_KernelDevDebugContainer([
    'container.build_hash' => 'MMBCceX',
    'container.build_id' => '2e387a88',
    'container.build_time' => 1743942084,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMMBCceX');
