<?php

namespace ContainerBAqn0O7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YooyB2kService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yooyB2k' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yooyB2k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trottinetteRepository' => ['privates', 'App\\Repository\\TrottinetteRepository', 'getTrottinetteRepositoryService', true],
        ], [
            'trottinetteRepository' => 'App\\Repository\\TrottinetteRepository',
        ]);
    }
}
